services:
  labfooddesk:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      # args:
      #   NEXT_PUBLIC_CLIENTVAR: "clientvar"
    working_dir: /app
    ports:
      - "3000:3000"
    image: labfooddesk
    env_file:
      - .env
    environment:
      - DATABASE_URL=file:/app/db/db.sqlite
volumes: 
  postgres_data: