version: "3.9"
services:
  app:
    restart: always
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile-app
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    working_dir: /app
    ports:
      - "3000:3000"
    image: t3-app
    environment:
      - DATABASE_URL=database_url_goes_here
  db:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-db
    volumes:
        - postgres_data:/var/lib/postgresql/data/
    env_file:
        - ./.env
volumes: 
  postgres_data: 